eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
server:
  port: 9108
logging:
  config: classpath:logback.xml


spring:
    application:
        name: consumer
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        name: optest
        url: jdbc:mysql://localhost:3306/secondskill?characterEncoding=UTF-8&tinyInt1isBit=false
        username: root
        password: tiger
        driver-class-name: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      #数据库链接池配置为Tomcat线程池的1/10,由于数据库响应较快，设1数据库链接链接为10个Web线程服务.
      # 初始化大小，最小，最大，
        initialSize: 10
        minIdle: 6
        maxActive: 30
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
        validationQuery: SELECT 1 FROM DUAL
        # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
        testWhileIdle: true
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnBorrow: false
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # druid用户名
        druidUserName: anchi
        # druid密码
        druidPassword: Allcitygo001
        # druid允许远程连接
        druidEnableRemote: false
    # redis配置，以下有默认配置的也可以使用默认配置
swagger:
  enable: true
mybatis:
  mapper-locations: classpath:mapper/*/*.xml

